### ISSUE TITLE
KeePass warns HIBPOfflineCheck.dll is incompatible with the current KeePass version

### ISSUE THREAD

**Issue by gusbrown** [mihaifm/HIBPOfflineCheck#33] opened 2019-04-26 18:24 UTC
KeePass version: 2.41
HIBPOfflineCheck version: 1.5.0.0

I'm able dismiss the warning three times and am then able to open KeePass and use the HIBP plugin as expected.

Here is the full message:
Keepass 

The following plugin is incompatible with the current Keepass 
version: 
C:\Users\*myprofile*\AppData\Local\KeePass\HIPBOfflineCheck.dll 

Have a look at the plugin's website for an appropriate version. 

Value cannot be null. 
Parameter name: prov 
Keepass 
 at KeePass.UI.ColumnProviderPool.Remove(ColumnProvider prov) 
at HIBPOfflineCheck.HIBPOfflineCheckExt.Terminate() 
at HIBPOfflineCheck.HIBPOfflineCheckExtCheckExt.Initialize(IPIuginHost host) 
at KeePass.Plugins.PluginManager.LoadPlugins(List'1 IFiIes, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiIes) Boolean Remove(KeePass.UI.ColumnProvider)

**Comment by mihaifm** [comment] 2019-04-26 19:33
Weird, does this happen every time?
Maybe it’s some caching issue.

**Comment by gusbrown** [comment] 2019-04-26 19:37
It displays the same error 3 times each time I launch KeePass.  This has persisted through the last two versions of KeePass and HIBPOfflineCheck (but I did not experience after first installing the plugin).

**Comment by mihaifm** [comment] 2019-04-28 08:46
It could be related to .NET versions, since the latest versions of the plugin require .NET 4.5

See this discussion, there’s an advice to comment out older .NET versions from `keepass.exe.config`, maybe it helps:

https://sourceforge.net/p/keepass/discussion/329220/thread/c00b8889/

**Comment by boldt** [comment] 2019-07-13 15:31
I can confirm that issue:

* Ubuntu 18.04
* KeePass version: 2.41
* HIBPOfflineCheck version: 1.5.1 / 1.6.0

![Bildschirmfoto von 2019-07-13 17-28-47](https://user-images.githubusercontent.com/750793/61173466-fa528b80-a593-11e9-9cce-69b75c82252b.png)

**Comment by boldt** [comment] 2019-07-13 15:51
I installed `mono-complete` and it starts now.

**Comment by samdark** [comment] 2019-08-17 16:58
Does not happen under Windows.

**Comment by ggaussling** [comment] 2019-10-05 15:16
Hi, I got the same issue on Windows 10 1903 build 18362.388, .NET Framework >=4.8 (true, powershell ReleaseKey >= 528040) and KeePass 2.43. 

I put the old plugin files in a subfolder and I had to rename the files in that subfolder in order to avoid KeePass to load them I guess. Because after I renamed them the error was gone.

`$ tree "C:\Program Files (x86)\KeePass Password Safe 2\Plugins"
C:\Program Files (x86)\KeePass Password Safe 2\Plugins
├── HaveIBeenPwned.plgx
├── HIBPOfflineCheck.plgx
├── KeePassHIBP.plgx
├── KeePassQuickUnlock.plgx
├── MinLock.plgx
├── old
│   ├── __1.3.1_HaveIBeenPwned.plg_x_
│   ├── __HIBPOfflineCheck.plg_x_
│   ├── _HaveIBeenPwned.plg_x_
│   └── _HIBPOfflineCheck.plg_x_
├── OnScreenKeyboard2.plgx
└── OnScreenKeyboard2_ReadMe.html

1 directory, 11 files`


![2019-10-05 16_46_45-KeePass](https://user-images.githubusercontent.com/1688321/66256894-247ea880-e793-11e9-9537-573815a006ce.png)

![2019-10-05 16_48_42-Update Check - KeePass](https://user-images.githubusercontent.com/1688321/66256903-35c7b500-e793-11e9-952d-e22ee86dc49a.png)

![2019-10-05 16_52_13-HIBP Offline Check](https://user-images.githubusercontent.com/1688321/66256906-39f3d280-e793-11e9-9e5d-1e163aded370.png)

Anyway the plugin seemed to load, whether it was renamed or not, despite the error. But renamed also haveIbeenPwned checker loaded the new version from the top folder, and the message was gone.

Just for your information.

**Comment by cristianst85** [comment] 2022-12-29 05:25
Is there anything to be done with this issue, or can it be closed?

**Comment by boldt** [comment] 2023-01-03 09:47
It still happend on a clean Ubuntu installation:

* Ubuntu version: 22.04.1 LTS
* KeePass version: 2.47
* HIBPOfflineCheck version: 1.7.9

As before, installing `mono-complete` makes it working.

**Comment by cristianst85** [comment] 2023-01-03 11:33
Hi there!

From what I understand, that's not an issue with the plugin itself, but with some prerequisite (i.e., `mono-complete`) that is missing. Isn't? Maybe updating the README.md with this info helps?

**Comment by boldt** [comment] 2023-01-03 12:53
Yes, that would help!

**Comment by cristianst85** [comment] 2023-01-03 13:57
I don't have or use Ubuntu, but...

I've installed a fresh instance of OpenSUSE Leap 15.4 x64 (with KDE).
Via YaST Control Center -> Software -> Software Management -> I can install `KeePass 2.49-bp154.1.70`, which pulls all mono dependencies, but without the `mono-complete` package.
Also, `keepass-plugin-HIBPOfflineCheck 1.7.6-bp154.1.52` is available as a package that installs fine with no additional dependencies being installed or required)

Additionally, I've built the latest version of `HIBPOfflineCheck` from the `master` branch and replaced the `/usr/lib/keepass/HIBPOfflineCheck.dll`, which loads without any issues. I have also tested the `plgx` version and had the same result - no errors.

`mono --version` outputs `Mono JIT compiler version 6.8.0.105 (tarball Sat Jun  6 02:05:47 UTC 2020)`

I find it weird that Ubuntu requires different packages. What version of mono do you have installed?

![image](https://user-images.githubusercontent.com/12585988/210368502-2ab170bc-efb4-4ca3-be37-de52af116a59.png)

![image](https://user-images.githubusercontent.com/12585988/210368519-d6ff0533-a4a7-431e-bb3f-6eb63c72bad6.png)

![image](https://user-images.githubusercontent.com/12585988/210369587-50f73a17-a8c9-4efc-9dd3-569521bf1017.png)

**Comment by cristianst85** [comment] 2023-01-03 14:27
From https://www.mono-project.com/download/stable/#download-lin-ubuntu - it appears that the recommendation with `mono` is to install `mono-complete` to install everything.

> The package mono-complete should be installed to install everything - this should cover most cases of "assembly not found" errors.

**Comment by boldt** [comment] 2023-01-03 14:28
I'll run a test on another Ubuntu system to figure out, which exact package is missed, since the `mono-complete` seems a bit to much.

**Comment by cristianst85** [comment] 2023-01-03 14:32
Okay, we may have posted at the same time. As I said above, it appears that the recommendation with `mono` is to install `mono-complete` to install everything (see [here](https://www.mono-project.com/download/stable/#download-lin-ubuntu)). In any case, the issue seems to be with how the packages are built on various Linux distributions which is a bit out of scope.

**Comment by cristianst85** [comment] 2023-01-03 15:05
What is interesting is if that I build the plugin PLGX with `--plgx-prereq-net:4.5` I get this nice error. Which doesn't get away if I install `mono-complete`.

![image](https://user-images.githubusercontent.com/12585988/210383722-3fb364d1-a652-4feb-a352-a1328a8fd186.png)

**Comment by cristianst85** [comment] 2023-01-03 17:23
I have asked Dominik Reichl whether the `--plgx-prereq-net` build flag is supposed to work with Mono as well, and he said that this was added only in KeePass 2.52 (see his answer [here](https://sourceforge.net/p/keepass/discussion/329221/thread/9a760d7b/?limit=25#e40e)). My idea of adding `--plgx-prereq-net:4.5` when creating the PLGX is to make KeePass show a detailed error message to the end-user (instead of a generic plugin incompatibility message). This should work fine on Windows since many probably use a more recent version of KeePass anyway. But on Linux, it breaks the plugin if an older version of KeePass is used (older than the latest version which is 2.52) which will be the most distros I assume.

**Comment by boldt** [comment] 2023-01-03 21:15
I assume, keepass2 on Suse installs more dependend packages than Ubuntu.

`mono --version` under Ubuntu 22.04:

```
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.2 Wed Jun 30 05:34:49 UTC 2021)
```

Here the dependencies installed by **keepass2**:

```
$ apt-cache showpkg keepass2
Package: keepass2
Versions: 
2.47+dfsg-2
[...]
Dependencies: 
2.47+dfsg-2 - mono-runtime (2 3.0~) libgcrypt20 (2 1.8.7) libmono-corlib4.5-cil (2 5.18.0.240) libmono-system-drawing4.0-cil (2 5.12.0.309) libmono-system-security4.0-cil (2 5.18.0.240) libmono-system-windows-forms4.0-cil (2 5.16.0.220) libmono-system-xml4.0-cil (2 4.6.1.3) libmono-system4.0-cil (2 5.18.0.240) libx11-6 (2 2:1.6.0) xsel (0 (null)) keepass2-doc (0 (null)) mono-dmcs (0 (null)) xdotool (0 (null)) 
```

So, on Ubuntu, it just installs `mono-runtime` and some dependencies (`ibmono-`).

https://unix.stackexchange.com/questions/282329/is-the-difference-between-mono-runtime-and-mono-complete-related-to-whether-mysq

**Comment by boldt** [comment] 2023-01-03 21:18
![Bildschirmfoto vom 2023-01-03 22-13-44](https://user-images.githubusercontent.com/750793/210442626-0303c4ff-877f-4331-aee9-1da85fdca1a3.png)

Observation: It says, **compiling**. Are keepass plugins compiled on runtime?

Looking into `mono-complete`, it also installs `mono-devel`. If I install `mono-devel` (still a meta package with a lot of dependencies), this plugin works.

**Comment by cristianst85** [comment] 2023-01-03 21:21
The PLGX version of the plugin(s) is(are) compiled once when KeePass loads.

**Comment by boldt** [comment] 2023-01-03 21:42
### For documentation

The compiled plugins can be found here:

```
~/.local/share/KeePass/PluginCache/
```

### Debugging

Thanks for the link it says:

```
PLGX debugging. When the command line option --debug is passed and a PLGX plugin fails to compile, the output of all tried compilers is saved to a temporary file.
```
* I removed the compiled dll 
* I removed package `mono-devel` and all its dependencies
* I added `--debug` 

A log file was created. It says:

```
error CS0006: Metadata file `System.DirectoryServices.dll' could not be found
```

**Comment by cristianst85** [comment] 2023-01-03 21:45
Indeed `HIBPOfflineCheck` has a reference to `System.DirectoryServices.dll`. Not sure why since it builds without it just fine.

**Comment by boldt** [comment] 2023-01-03 21:47
Can you prove me a PLGX without the `System.DirectoryServices.dll` , so I can test it?

**Comment by cristianst85** [comment] 2023-01-03 21:57
I did some cleanup. Removed three unneeded references. You can see the changes on this temporary branch/[commit](https://github.com/cristianst85/HIBPOfflineCheck/commit/da9addbdd025cb4546b41554ea755a39f83333b8).

You must unzip it first. Otherwise, GitHub won't let me attach the file here.

[HIBPOfflineCheck-1.7.9.da9addb.zip](https://github.com/mihaifm/HIBPOfflineCheck/files/10340041/HIBPOfflineCheck-1.7.9.da9addb.zip)

**Comment by boldt** [comment] 2023-01-03 22:04
Yes, it works without `mono-devel`.

**Comment by cristianst85** [comment] 2023-01-03 22:08
What about the `mono-complete` package, is that still required?

**Comment by boldt** [comment] 2023-01-03 22:11
`mono-complete` is not required as well.

**Comment by boldt** [comment] 2023-01-03 22:12
I'll double check your PLGX on another system tomorrow.

**Comment by cristianst85** [comment] 2023-01-03 22:33
> I assume, keepass2 on Suse installs more dependend packages than Ubuntu.

Probably not relevant anymore, but just for documentation purposes. On OpenSUSE Leap 15.4, when installing KeePass zypper also resolves the following packages.


```
localhost:~ # zypper in keepass
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following recommended package was automatically selected:
  xdotool

The following 14 NEW packages are going to be installed:
  keepass libgdiplus-devel mono-core mono-data mono-data-oracle mono-data-sqlite mono-devel mono-extras mono-mvc mono-wcf mono-web mono-winforms mono-winfxcore xdotool

14 new packages to install.
Overall download size: 47.1 MiB. Already cached: 0 B. After the operation, additional 205.6 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): n
localhost:~ # 
```

**Comment by boldt** [comment] 2023-01-03 22:43
So, `mono-devel` is a dependency of keepass on Suse.

**Closed** 2023-01-04 09:52 UTC

**Comment by boldt** [comment] 2023-01-04 21:57
I ran a test on an Ubuntu live system:

* I installed KeePass2
* I installed the PLGX you provided

And it's not working out if the box!

I further investigated in this issue, and I tracked it down to the package `mono-mcs`, which is the c# compiler  (which also part of `mono-devel`). It was still installed on my system.

I highly recommend to add a hint to the README, that `mono-mcs` is required.

**Comment by cristianst85** [comment] 2023-01-04 22:25
Thank you for your effort!

Just to clarify, do you mean `mono-devel`? Because I see no standalone package `mono-mcs` (at least in OpenSUSE Leap 15.4).

**Comment by boldt** [comment] 2023-01-04 22:31
I really mean `mono-mcs`, whch is a separate package on Ubuntu: https://packages.ubuntu.com/bionic/mono-mcs

Can you double check on Suse, since your output contains the package:

```
> > I assume, keepass2 on Suse installs more dependend packages than Ubuntu.
> 
> Probably not relevant anymore, but just for documentation purposes. On OpenSUSE Leap 15.4, when installing KeePass zypper also resolves the following packages.
> 
> ```
> localhost:~ # zypper in keepass
> Loading repository data...
> Reading installed packages...
> Resolving package dependencies...
> 
> The following recommended package was automatically selected:
>   xdotool
> 
> The following 14 NEW packages are going to be installed:
>   keepass libgdiplus-devel mono-core mono-data mono-data-oracle mono-data-sqlite mono-devel mono-extras mono-mvc mono-wcf mono-web mono-winforms mono-winfxcore xdotool
> 
> 14 new packages to install.
> Overall download size: 47.1 MiB. Already cached: 0 B. After the operation, additional 205.6 MiB will be used.
> Continue? [y/n/v/...? shows all options] (y): n
> localhost:~ # 
> ```

**Comment by boldt** [comment] 2023-01-04 22:42
Maybe the hint is just necessary for Ubuntu/Debian, since KeePass2 installs `mono-devel` on Suse.

**Comment by cristianst85** [comment] 2023-01-04 23:10
Yeah, it seems that the package content is different and also the naming. Ubuntu has `mono-runtime`, which seems to be the equivalent of `mono-core` on OpenSUSE. I will create another PR tomorrow.

**Comment by mihaifm** [comment] 2023-01-05 11:25
Thanks guys
